// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/greeting.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GreetingServiceRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingServiceRequest) Reset()         { *m = GreetingServiceRequest{} }
func (m *GreetingServiceRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingServiceRequest) ProtoMessage()    {}
func (*GreetingServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e54e98d9a01155c, []int{0}
}

func (m *GreetingServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingServiceRequest.Unmarshal(m, b)
}
func (m *GreetingServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingServiceRequest.Marshal(b, m, deterministic)
}
func (m *GreetingServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingServiceRequest.Merge(m, src)
}
func (m *GreetingServiceRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingServiceRequest.Size(m)
}
func (m *GreetingServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingServiceRequest proto.InternalMessageInfo

func (m *GreetingServiceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreetingServiceReply struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingServiceReply) Reset()         { *m = GreetingServiceReply{} }
func (m *GreetingServiceReply) String() string { return proto.CompactTextString(m) }
func (*GreetingServiceReply) ProtoMessage()    {}
func (*GreetingServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_6e54e98d9a01155c, []int{1}
}

func (m *GreetingServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingServiceReply.Unmarshal(m, b)
}
func (m *GreetingServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingServiceReply.Marshal(b, m, deterministic)
}
func (m *GreetingServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingServiceReply.Merge(m, src)
}
func (m *GreetingServiceReply) XXX_Size() int {
	return xxx_messageInfo_GreetingServiceReply.Size(m)
}
func (m *GreetingServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingServiceReply proto.InternalMessageInfo

func (m *GreetingServiceReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetingServiceRequest)(nil), "GreetingServiceRequest")
	proto.RegisterType((*GreetingServiceReply)(nil), "GreetingServiceReply")
}

func init() { proto.RegisterFile("proto/greeting.proto", fileDescriptor_6e54e98d9a01155c) }

var fileDescriptor_6e54e98d9a01155c = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x2f, 0x4a, 0x4d, 0x2d, 0xc9, 0xcc, 0x4b, 0xd7, 0x03, 0x73, 0x95, 0x74, 0xb8,
	0xc4, 0xdc, 0xa1, 0x22, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x41, 0xa9, 0x85, 0xa5, 0xa9,
	0xc5, 0x25, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x60, 0xb6, 0x92, 0x01, 0x97, 0x08, 0x86, 0xea, 0x82, 0x9c, 0x4a, 0x21, 0x09, 0x2e, 0xf6,
	0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26, 0xb0, 0x72, 0x18, 0xd7, 0xc8, 0x9f, 0x8b,
	0x1f, 0x4d, 0x87, 0x90, 0x0d, 0x17, 0x07, 0x4c, 0x48, 0x48, 0x5c, 0x0f, 0xbb, 0xed, 0x52, 0xa2,
	0x7a, 0xd8, 0x2c, 0x52, 0x62, 0x70, 0xe2, 0x8c, 0x62, 0xd7, 0xd3, 0x07, 0xbb, 0x3d, 0x89, 0x0d,
	0x4c, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x11, 0xc9, 0x7d, 0xda, 0x00, 0x00, 0x00,
}
